version: "3.3"

services:
  colors-of-cuisine:
    build: ./products
    image: chenv/colors-of-cuisine:v1.0.2
    ports:
      - 5001:3000

  application:
    build: ./application
    image: chenv/application:v1.0.2
    ports:
      - 5000:80
    depends_on:
      - colors-of-cuisine